os: linux
dist: bionic

language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.gradle

before_script:
  - chmod +x gradlew

script: ./gradlew check --console=plain

deploy:
  provider: script
  script: ./gradlew bintrayUpload --console=plain
  skip_cleanup: true
  on:
    branch: master
    tags: true
